### ISSUE TITLE
pybullet : kukaGymEnv and kukaCamGymEnv doesn't converge

### ISSUE THREAD

**Issue by k123jack** [bulletphysics/bullet3#1418] opened 2017-11-02 02:12 UTC
I was trying to run the original tarin_kuka_grasping.py. However, after 10000000 steps training it didn't converge. 
I also modificated the kukaCamGymEnv , to get the end-effector view image as observation, but the mean 100 episode reward seems doesn't converge either.
Should I try something more advanced algorithms such as A3C? However, the Baselines supports multi-thread Atari , but I don't know how to adapt the kukaCamGymEnv to it, anybody can help.

**Comment by erwincoumans** [comment] 2017-11-02 02:17
This is a duplicate of https://github.com/bulletphysics/bullet3/issues/1386
I just uploaded a new version of the Kuka grasping environment, both discrete and continuous.
Let's first try to get the kukaGymEnv to train properly, then later we look into kukaCamGymEnv .

**Closed by erwincoumans** 2017-11-02 02:17 UTC
