### ISSUE TITLE
pybullet_envs not rendering

### ISSUE THREAD

**Issue by BruceK4t1qbit** [bulletphysics/bullet3#2107] opened 2019-02-12 21:46 UTC
Here's my code

![image](https://user-images.githubusercontent.com/39970654/52670124-a6e8ee00-2ecc-11e9-854d-092d13ec5796.png)

**Comment by BruceK4t1qbit** [comment] 2019-02-12 21:49
It does work if I add the env.render() before the env.reset(), rather than each time I want to render.

Is this the intended behaviour?

![image](https://user-images.githubusercontent.com/39970654/52670237-e0b9f480-2ecc-11e9-8715-b1fb84f5b159.png)

**Comment by erwincoumans** [comment] 2019-02-12 22:17
Yes, that is the intended behavior. Problem is that Gym doesn't have a boolean render when creating the environment. Bullet needs to enable rendering at initialization, not afterwards.

It requires a lot of changes, to allow opening/closing a render window at any time, so for now, using the 'render' before first reset is needed.

**Closed by erwincoumans** 2019-02-12 22:17 UTC

**Comment by BruceK4t1qbit** [comment] 2019-02-13 02:39
Can I add a check, or a print statement to this effect?  To save the next person a couple hours?
