### ISSUE TITLE
Bug: small vibrations when clicking with the mouse

### ISSUE THREAD

**Issue by bdelhaisse** [bulletphysics/bullet3#1817] opened 2018-08-03 02:04 UTC
Hi,

I have loaded a robotic hand in Pybullet. When setting the joint positions to some values, and letting the simulator run, the robot shakes as depicted below:
![robot-shake](https://user-images.githubusercontent.com/15890452/43620104-6f76e316-96d1-11e8-8f8d-340c94c2c328.gif)

Next, by clicking with the left button on the mouse in the world, I have some joints that jump. This is depicted below (everytime the thumb jumps, it is because I clicked):
![joint-jump](https://user-images.githubusercontent.com/15890452/43620244-08856fe6-96d2-11e8-91fc-46e3a7739a09.gif)
I don't have this when clicking with the scroll or right button.

I found out that these behaviors appear when I fix the base in the world by setting `useFixedBase` to `True` when loading the URDF. If there would be a way to solve this problem, it would be nice. 

Thanks.

**Comment by erwincoumans** [comment] 2018-08-16 17:04
Can you share the URDF/PyBullet file to see if we can reproduce the problem? Also, we fixed some issues recently, are you using the very latest version of PyBullet? pybullet 2.1.2 or later?

**Comment by erwincoumans** [comment] 2018-08-31 03:36
It is likely due to a constraint added between a fixed body and the fixed world. We should avoid adding such constraint.

**Comment by erwincoumans** [comment] 2018-12-22 20:01
We cannot take action without a small reproduction case. Let's close it.

**Closed by erwincoumans** 2018-12-22 20:01 UTC

**Comment by v-wewei** [comment] 2021-01-23 16:17
Hi, @erwincoumans,  i meet the same problem recently. when i create some constriants between two joints for each finger in  a robotics hand. Some of the joint show unresonable behaviour. When i click on my hand, the ring (fourth) finger got shaked at same time, corresponding joint index pair is (16, 17)
the code is shown as blew.
    cid_thumb = p.createConstraint(hithandId, 4, hithandId, 5, jointType=p.JOINT_GEAR,
                                   jointAxis=[1, 0, 0],
                                   parentFramePosition=[0, 0, 0],
                                   childFramePosition=[0, 0, 0],
                                   )
    p.changeConstraint(cid_thumb, gearRatio=-1.0, erp=2.0, maxForce=1500)
   
    cid_fore = p.createConstraint(hithandId, 8, hithandId, 9, jointType=p.JOINT_GEAR,
                                  jointAxis=[1, 0, 0],
                                  parentFramePosition=[0, 0, 0],
                                  childFramePosition=[0, 0, 0],
                                  )
    p.changeConstraint(cid_fore, gearRatio=-1.0, erp=2.0, maxForce=1500)
  
    cid_middle = p.createConstraint(hithandId, 12, hithandId, 13, jointType=p.JOINT_GEAR,
                                    jointAxis=[1, 0, 0],
                                    parentFramePosition=[0, 0, 0],
                                    childFramePosition=[0, 0, 0],
                                    )
    p.changeConstraint(cid_middle, gearRatio=-1.0, erp=2.0, maxForce=1500)
    
    cid_ring = p.createConstraint(hithandId, 16, hithandId, 17, jointType=p.JOINT_GEAR,
                                  jointAxis=[1, 0, 0],
                                  parentFramePosition=[0, 0, 0],
                                  childFramePosition=[0, 0, 0],
                                  )
    p.changeConstraint(cid_ring, gearRatio=-1.0, erp=2.0, maxForce=1500)
    
    cid_little = p.createConstraint(hithandId, 20, hithandId, 21, jointType=p.JOINT_GEAR,
                                    jointAxis=[1, 0, 0],
                                    parentFramePosition=[0, 0, 0],
                                    childFramePosition=[0, 0, 0],
                                    )
    p.changeConstraint(cid_little, gearRatio=-1.0, erp=2.0, maxForce=1500)

but if only create costraint for joint  (16, 17) , it works.
